import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Recursive } from "next/font/google"

// const inter = Inter({ subsets: ["latin"] });

const roboto = Recursive({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800', '900', '1000']
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>{children}</body>
		</html>
	);
}
